# Generated by Django 4.2.1 on 2023-05-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musterpoint_2_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wargear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('range', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('strength', models.CharField(max_length=100)),
                ('armor_penetration', models.IntegerField()),
                ('damage', models.CharField(max_length=200)),
                ('abilities', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='unitdatasheet',
            name='wargear_options',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='unitdatasheet',
            name='wargear_options_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OptionalWargear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon', models.CharField(max_length=100)),
                ('unit', models.ManyToManyField(related_name='optional_wargear', to='musterpoint_2_app.unitdatasheet')),
            ],
        ),
        migrations.CreateModel(
            name='FixedWargear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_weapon', models.CharField(max_length=100)),
                ('unit', models.ManyToManyField(related_name='wargear', to='musterpoint_2_app.unitdatasheet')),
            ],
        ),
    ]
