# Generated by Django 4.2.1 on 2023-05-22 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musterpoint_2_app', '0002_wargear_unitdatasheet_wargear_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionalwargear',
            name='unit',
        ),
        migrations.DeleteModel(
            name='FixedWargear',
        ),
        migrations.DeleteModel(
            name='OptionalWargear',
        ),
    ]
