# Generated by Django 4.2.1 on 2023-05-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musterpoint_2_app', '0003_remove_optionalwargear_unit_delete_fixedwargear_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitdatasheet',
            name='upgrades',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='unitdatasheet',
            name='upgrades_points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
