# Generated by Django 4.2.1 on 2023-05-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musterpoint_2_app', '0004_unitdatasheet_upgrades_unitdatasheet_upgrades_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitdatasheet',
            name='upgrades_points',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='unitdatasheet',
            name='wargear_options_points',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
