# Generated by Django 4.2.1 on 2023-05-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musterpoint_2_app', '0005_alter_unitdatasheet_upgrades_points_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociatedWargear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associated_wargear', models.CharField(max_length=100)),
                ('unit', models.ManyToManyField(related_name='wargear', to='musterpoint_2_app.unitdatasheet')),
            ],
        ),
    ]
