# Generated by Django 4.1.3 on 2023-05-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musterpoint_2_app', '0006_associatedwargear'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
